### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Bico
email: your-email@example.com
description:  Everything you need for a successful ICO in the first ICO funded book
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bico.me" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#4848B4'
twitter_username: BicoTeam
github_username:  BicoTeam
author: Sandoche Adittane
logo: assets/images/large-logo.png
twitter:
  username: BicoTeam
social:
  name: Sandoche Adittane
  links:
    - https://twitter.com/BicoTeam
    - https://bicotoken.slack.com/join/shared_invite/MjM1MDk4NDY1NjY1LTE1MDQ0NTAyMTItZWZjNDkwYzIyOA
    - https://www.facebook.com/bicotoken/
    - https://github.com/BicoTeam

languages: ["en"]
ampdir: amp

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
google_analytics: UA-105835474-1
doorbell: gNPcVwNLbPsu696OYfSe689CSkN21pZwamPT3pxGgBhKoUsLSHmQS6Yp9Bo9Vmqj
cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - jekyll-multiple-languages-plugin
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
